# ----------------------------
# Makefile Options
# ----------------------------

NAME = SNAKE
ICON = icon.png
DESCRIPTION = "Snake Game"
COMPRESSED := YES
ARCHIVED = NO 

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# This Actually Works!!!
HAS_PRINTF := NO

# ----------------------------

include $(shell cedev-config --makefile)
