#ifndef MEM_CHANNELS_H
#define MEM_CHANNELS_H

#include <cutil/misc.h>

#define MS_GAME_CHANNEL         FREE_CHANNEL(0)
#define MS_WINDOW_CHANNEL       FREE_CHANNEL(1) 
#define MS_SCORES_CHANNEL       FREE_CHANNEL(2)
#define GAMEMODE_CHANNEL        FREE_CHANNEL(3)
#define GAMEPLAY_CHANNEL        FREE_CHANNEL(4)
#define HOMEPAGE_CHANNEL        FREE_CHANNEL(5)
#define HIGHSCORES_CHANNEL      FREE_CHANNEL(6)
#define VICTORY_CHANNEL         FREE_CHANNEL(7)
#define DEFEAT_CHANNEL          FREE_CHANNEL(8)
#define INSTRUCTIONS_CHANNEL    FREE_CHANNEL(9)

#endif
